
export interface Log {
    status: number,
    logType: string,
    level: string,
    request: any,
    response: any,
    api: string,
    func: string,
    timeTaken: number,
    userId?: string,
    sessionId?: string,
    bookingId?: string,
    userSessionId?: string,
    apiSessionId?: string,
    error: any,
    stackTrace?: any,
    errorCode: number,
    endUserIp?: string,
    url?: string,
    appVersion?: string,
    method?: string,
    arg?: any,
    loggedInUserId?: string,
    source?: string,
    platform?: string
}

export interface ESLogModel {
    type: string,
    env: string,
    module: string
    binary_request: any,
    binary_response: any,
    time_stamp: any,
    status: number,
    level: string,
    time_taken: number,
    platform: string,
    api?: string,
    func?: string,
    logged_in_user_id?: any,
    user_id?: any,
    session_id?: any,
    booking_id: any,
    api_session_id: any,
    user_session_id: any,
    origin?: any,
    destination?: any,
    error_code?: number,
    error?: any,
    stack_trace?: any,
    contact_email?: any,
    contact_phone?: any,
    contact_name?: any,
    payment_provider?: any,
    endUserIp?: string,
    url?: string,
    source: string,
    appVersion?: string,
    arg?: any
}
